import jsPDF from "jspdf";
import Plotly from "plotly.js-dist-min";

import { Api, type Report } from "@/api/client";

const CHART_KINDS = [
  { kind: "equity",         label: "Equity Curve"    },
  { kind: "drawdown",       label: "Drawdown"        },
  { kind: "heatmap",        label: "Monthly Returns" },
  { kind: "trade_pnl",      label: "Trade P&L"       },
  { kind: "rolling_sharpe", label: "Rolling Sharpe"  },
] as const;

const PAGE_W = 595.28;   // A4 portrait, in pt
const PAGE_H = 841.89;
const MARGIN = 48;
const CONTENT_W = PAGE_W - MARGIN * 2;
const FOOTER_RESERVE = 36;

const COLOR_INK = "#1f2937";
const COLOR_MUTED = "#6b7280";
const COLOR_ACCENT = "#0891b2";

export async function exportReportPdf(runId: number, report: Report): Promise<void> {
  const [run, assets, ...figures] = await Promise.all([
    Api.getBacktest(runId),
    Api.listAssets(),
    ...CHART_KINDS.map((c) => Api.getChart(runId, c.kind)),
  ]);

  const asset = assets.find((a) => a.id === run.asset_id);

  const images = await Promise.all(
    figures.map((f) =>
      Plotly.toImage(
        { data: f.figure.data as Plotly.Data[], layout: f.figure.layout as Partial<Plotly.Layout> },
        { format: "png", width: 1000, height: 520, scale: 2 },
      ),
    ),
  );

  const doc = new jsPDF({ unit: "pt", format: "a4" });
  let y = MARGIN;

  y = drawCover(doc, y, {
    runId,
    asset: asset?.symbol ?? `asset #${run.asset_id}`,
    assetName: asset?.name,
    startDate: run.start_date,
    endDate: run.end_date,
    timeframe: run.timeframe,
    model: report.model,
    generatedAt: report.generated_at,
    demoMode: report.demo_mode,
  });

  CHART_KINDS.forEach((c, i) => {
    y = drawChart(doc, y, c.label, images[i]);
  });

  y = ensureSpace(doc, y, 40);
  y = drawHeading(doc, y, "AI Analysis", 16);
  y = drawMarkdown(doc, y, report.text);

  drawDisclaimerFooterOnAllPages(doc);

  doc.save(`backtest-run-${runId}.pdf`);
}

// -----------------------------------------------------------------------------
// Drawing helpers
// -----------------------------------------------------------------------------

interface CoverData {
  runId: number;
  asset: string;
  assetName?: string;
  startDate: string;
  endDate: string;
  timeframe: string;
  model: string;
  generatedAt: string;
  demoMode: boolean;
}

function drawCover(doc: jsPDF, y: number, c: CoverData): number {
  doc.setTextColor(COLOR_ACCENT);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.text("Backtest Report", MARGIN, y);
  y += 26;

  doc.setTextColor(COLOR_MUTED);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(`Run #${c.runId}`, MARGIN, y);
  y += 18;

  const rows: [string, string][] = [
    ["Asset",     c.assetName ? `${c.asset} — ${c.assetName}` : c.asset],
    ["Timeframe", c.timeframe === "1h" ? "Hourly" : "Daily"],
    ["Range",     `${c.startDate.slice(0, 10)} → ${c.endDate.slice(0, 10)}`],
    ["Model",     `${c.model}${c.demoMode ? "  (demo mode)" : ""}`],
    ["Generated", new Date(c.generatedAt).toLocaleString()],
  ];

  doc.setFontSize(11);
  for (const [k, v] of rows) {
    doc.setTextColor(COLOR_MUTED);
    doc.text(k, MARGIN, y);
    doc.setTextColor(COLOR_INK);
    doc.text(v, MARGIN + 86, y);
    y += 16;
  }

  if (c.demoMode) {
    y += 4;
    doc.setTextColor("#b45309");
    doc.setFontSize(9);
    doc.text(
      "Demo mode: report was generated by the NullProvider (no real LLM call).",
      MARGIN,
      y,
    );
    y += 14;
  }

  return y + 12;
}

function drawChart(doc: jsPDF, y: number, label: string, pngDataUrl: string): number {
  const imgH = CONTENT_W * (520 / 1000); // preserve 1000x520 aspect
  const blockH = 18 + 4 + imgH;
  y = ensureSpace(doc, y, blockH);

  doc.setTextColor(COLOR_INK);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text(label, MARGIN, y);
  y += 6;

  doc.addImage(pngDataUrl, "PNG", MARGIN, y, CONTENT_W, imgH);
  return y + imgH + 18;
}

function drawHeading(doc: jsPDF, y: number, text: string, size: number): number {
  y = ensureSpace(doc, y, size + 12);
  doc.setTextColor(COLOR_INK);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(size);
  doc.text(text, MARGIN, y + size * 0.8);
  return y + size + 10;
}

// Minimal markdown → jsPDF renderer. Handles # / ## / ### headings, blank-line
// paragraph breaks, and -/* bullet lists. Inline **bold** and *italics* markers
// are stripped (the report's hierarchy comes from headings, not emphasis).
function drawMarkdown(doc: jsPDF, y: number, md: string): number {
  const lines = md.replace(/\r\n/g, "\n").split("\n");

  for (const rawLine of lines) {
    const line = rawLine.trimEnd();

    if (line === "") {
      y += 6;
      continue;
    }

    const h3 = line.match(/^###\s+(.*)$/);
    const h2 = line.match(/^##\s+(.*)$/);
    const h1 = line.match(/^#\s+(.*)$/);
    const bullet = line.match(/^[-*]\s+(.*)$/);

    if (h1) {
      y = drawHeading(doc, y + 6, stripInline(h1[1]), 15);
      continue;
    }
    if (h2) {
      y = drawHeading(doc, y + 4, stripInline(h2[1]), 13);
      continue;
    }
    if (h3) {
      y = drawHeading(doc, y + 2, stripInline(h3[1]), 11);
      continue;
    }
    if (bullet) {
      y = drawBullet(doc, y, stripInline(bullet[1]));
      continue;
    }

    y = drawParagraph(doc, y, stripInline(line));
  }

  return y;
}

function drawParagraph(doc: jsPDF, y: number, text: string): number {
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10.5);
  doc.setTextColor(COLOR_INK);
  const wrapped = doc.splitTextToSize(text, CONTENT_W) as string[];
  for (const w of wrapped) {
    y = ensureSpace(doc, y, 14);
    doc.text(w, MARGIN, y + 10);
    y += 14;
  }
  return y + 2;
}

function drawBullet(doc: jsPDF, y: number, text: string): number {
  const indent = 14;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10.5);
  doc.setTextColor(COLOR_INK);
  const wrapped = doc.splitTextToSize(text, CONTENT_W - indent) as string[];
  for (let i = 0; i < wrapped.length; i++) {
    y = ensureSpace(doc, y, 14);
    if (i === 0) {
      doc.text("•", MARGIN + 2, y + 10);
    }
    doc.text(wrapped[i], MARGIN + indent, y + 10);
    y += 14;
  }
  return y + 2;
}

function stripInline(s: string): string {
  return s
    .replace(/\*\*([^*]+)\*\*/g, "$1")
    .replace(/(?<!\*)\*([^*]+)\*(?!\*)/g, "$1")
    .replace(/`([^`]+)`/g, "$1");
}

function ensureSpace(doc: jsPDF, y: number, needed: number): number {
  if (y + needed > PAGE_H - MARGIN - FOOTER_RESERVE) {
    doc.addPage();
    return MARGIN;
  }
  return y;
}

function drawDisclaimerFooterOnAllPages(doc: jsPDF): void {
  const pages = doc.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    doc.setFont("helvetica", "italic");
    doc.setFontSize(8);
    doc.setTextColor(COLOR_MUTED);
    doc.text(
      "AI analysis is not financial advice. Past performance does not guarantee future results.",
      MARGIN,
      PAGE_H - MARGIN + 6,
    );
    doc.text(`${i} / ${pages}`, PAGE_W - MARGIN, PAGE_H - MARGIN + 6, { align: "right" });
  }
}
